### ISSUE TITLE
Swift Package Manager Version Tags

### ISSUE THREAD

**Issue by anthonycastelli** [Prosumma/Iatheto#3]
I'm trying to add this as an SPM package to my project, however, im getting and error that it can not find a tag. Looking at the releases there appear to be tags with a pre-release and a v in front of v2. What is the latest tag? If it's v2.1, can that be tagged at 2.1.0 per sem-ver as SPM requires?

**Comment by Revolucent** [comment]
@anthonycastelli Just saw this. I can fix this for you, though it's probably too late. I didn't know SPM was so picky about semvers, while Carthage and CocoaPods are not.

**Comment by anthonycastelli** [comment]
Yeah, if you could tag it again that would be great! SPM is a little finicky with it, so having it tagged for me would be great!! 😊

**Comment by Revolucent** [comment]
Done. Now I have some work to do re-tagging some of my other open source projects.

**Comment by anthonycastelli** [comment]
Awesome! Thanks!! 😊
